### ISSUE TITLE
No `exists?` method

### ISSUE THREAD

**Issue by aglushkov** [resque/redis-namespace#172] opened 2020-06-30 07:18 UTC
Redis 4.2 warns :
  - `Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0

But changing `exists` to `exists?` shows redis-namespace error
  - Passing 'exists?' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0

**Comment by mperham** [comment] 2020-07-06 15:21
Dupe of #171

**Comment by rafaelfranca** [comment] 2020-08-19 15:52
#171 was merged. I'm going to release a new version soon

**Closed by rafaelfranca** 2020-08-19 15:52 UTC

**Comment by virusman** [comment] 2020-12-26 06:57
I'm still seeing this deprecation warning when using`redis-namespace` 1.8.0.

**Comment by reedstonefood** [comment] 2022-01-31 09:33
Also still happening in 1.8.1. @rafaelfranca WDYT?

> `Redis#exists(key)` will return an Integer in redis-rb 4.3, if you want to keep the old behavior, use `exists?` instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer = true. (/Users/reedstonefood/.gem/ruby/2.7.5/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:476:in `call_with_namespace')
